[features]
seeds = false
[programs.localnet]
fluid_staking = "HX1JgCTVJ3LiTFaua9J6zqjYWm2SsA1Cnac3qsH2XPcM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./auth.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
